### ISSUE TITLE
Localizable.strings usage

### ISSUE THREAD

**Issue by ivanzoid** [ustwo/US2FormValidator#12]
Hello, how do I put US2FormValidator Localizable.strings into my project?
I already have Localizable.strings in my project, I may try to add it to Copy Bundle Resources phase of root project, but it will overwrite my Localizable.strings file then. I may try to merge all localization files into one but probably I shouldn't as I'll need to do it again if I update US2FormValidator.

At this time NSLocalizedString(@"US2KeyConditionViolationEmail") gives me @"US2KeyConditionViolationEmail" instead @"Enter valid email address in the format example@example.com".

PS. Just found that it exists NSLocalizedStringFromTable (second argument is file name), I guess you may use it and rename US2FormValidator's Localizable.strings to some other name, and update instruction to copy this file to root project's bundle resources.

**Comment by alexfish** [comment]
Solved in pull request: https://github.com/ustwo/US2FormValidator/pull/13
