### ISSUE TITLE
Update CocoaPods/Specs project with latest podspecs

### ISSUE THREAD

**Issue by bachand** [ustwo/US2FormValidator#16]
Currently, versions 1.06, 1.07, and 1.08 of this project aren't available on CocoaPods.  The appropriate podspec files need to be added to the https://github.com/CocoaPods/Specs project.

**Comment by alexfish** [comment]
Totally forgot about doing this, sorry about that, waiting on the pull request to be merged on the spec repo then we are all good again.

**Comment by bachand** [comment]
Cool, no problem!

**Comment by alexfish** [comment]
Sorted: https://github.com/CocoaPods/Specs/pull/833

**Comment by bachand** [comment]
Great, pulled in 1.0.8 via CocoaPods and things seem to work fine!

**Comment by alexfish** [comment]
awesome!
