### ISSUE TITLE
US2EmptyValidator and US2EmptyCondition

### ISSUE THREAD

**Issue by bachand** [ustwo/US2FormValidator#18]
Wouldn't it make more sense if these were named `US2ValidatorNotEmpty` and `US2ConditionNotEmpty` (or `US2ValidatorPresent` and `US2ConditionPresent`, if we were to adopt  Rails terminology).  All of the other validators/conditions are named for the positive case (e.g. the `check` method of `US2ConditionEmail` returns `YES` if the string contains a valid email address, the `check` method of `US2ConditionNumeric` returns `YES` if the string contains only numeric characters, etc.).  However, as is, the `check` method for `US2ConditionEmpty` return `YES` if the string is **not** empty.  This inconsistency makes it confusing to use these classes.

**Comment by alexfish** [comment]
Yep I agree with you on this one.

**Comment by martinstolz** [comment]
Agree. I do not see a case to check positively for an empty text field but for checking a present string. But I would also discuss removing the US2ConditionEmpty entirely and not add US2ConditionPresent since you can use the US2ConditionRange.

US2ValidatorRange *rangeValidator = [[US2ValidatorRange alloc] init];
rangeValidator.range = NSMakeRange(1, NSIntegerMax);

We could create a US2ValidatorPresent which inherits or uses US2ValidatorRange.

Your thoughts?
@bachand
@alexefish
@mpurland

**Comment by bachand** [comment]
I like the simplicity of not adding a `US2ConditionPresent` class, but my concern with instead using `US2ConditionRange` is that the default error message will then be something cryptic like:

"Enter minimum 1, maximum 2147483647 characters" (2147483647 == `NSIntegerMax`)

whereas it would be nice if it were something more clear/simple like

"Can't be blank"

Obviously, we could override that message if we used `US2ConditionRange` in a `US2ValidatorPresent` class, but anyone who wanted to test for presence in a custom validator would then have to override the `US2ConditionRange` error message themselves.  Maybe a good alternative would be to make a `US2ConditionPresent` class that inherits from `US2ConditionRange`?  It could be a nice building block to have.

Either way, I definitely agree with getting rid of US2ConditionEmpty.

**Comment by svoctor** [comment]
Was there a decision on this? Removing US2ConditionEmpty sounds like a good idea, as well as the consistency discussed. Using US2ConditionPresent and US2ValidatorPresent instead works.

**Comment by bachand** [comment]
I think the consensus is to remove `US2ConditionEmpty`.  @alexefish @mpurland @martinstolz, since you guys are more involved in the codebase than me, what do you think about the proposals?  Do you think we should only add a `US2ValidatorPresent` or add a `US2ConditionPresent` as well?  I'm fine with either.

**Comment by alexfish** [comment]
Personally I think it makes sense to have an `US2ConditionPresent`, it is possible to get the same desired functionality with `US2ConditionRange` but using `US2ConditionPresent` makes it cleaner and as you say is a nice building block to have in place.

**Comment by bachand** [comment]
Assuming people are OK with that, are you planning on implementing that change?  Somewhat new to GitHub and not exactly sure how issues like this are resolved.

**Comment by alexfish** [comment]
Yeah no problem I'll take care of it, thanks for your input on this

**Comment by bachand** [comment]
No problem, let me know if you need any help.

**Comment by bachand** [comment]
Awesome, great!  Also, submitted a pull request (https://github.com/ustwo/US2FormValidator/pull/22) to update a few comments as well as the header file to use US2ConditionPresent/US2ValidatorPresent instead of US2ConditionEmpty/US2ValidatorEmpty.
