### ISSUE TITLE
US2ConditionRange broken for UITextView

### ISSUE THREAD

**Issue by adwell** [ustwo/US2FormValidator#24]
The regular expression should be `\\A.{%d,%d}\\Z`. Otherwise the range check only checks a single line instead of the entire length.

**Comment by adwell** [comment]
I think you'll need NSRegularExpressionDotMatchesLineSeparators too.

**Comment by alexfish** [comment]
Let's take a step back on this one, wouldn't simply checking `string.length` do the job?

**Comment by adwell** [comment]
Of course! Is there some reason it was using a regex?

**Comment by alexfish** [comment]
@martinstolz will be able to answer that one :smile:
