### ISSUE TITLE
CocoaPods and US2Localizable.strings - question

### ISSUE THREAD

**Issue by jupier** [ustwo/US2FormValidator#25]
Hey,

I would like to thank you for your library. 

I work on a project on which I need to change the "US2Localizable.strings" but it seems that it's impossible when I import the library with CocoaPods. Did you notice this bug ? Or have I something to do ?

MY US2Localizable.strings is present in my project and in MY Copy Bundle Resources. But when I modify the "US2KeyConditionViolationEmail" it does not appear in my project (delete the project from the simulator, clean, build : no effect) 

Regards,

Julien

**Comment by alexfish** [comment]
Sounds like a bug to me! I'll take a look into it for you.

**Comment by alexfish** [comment]
Does implementing [localizedViolationString:](https://github.com/ustwo/US2FormValidator/blob/master/US2FormValidationFramework/source/base/US2Condition.h#L78) also not work for you?

**Comment by jupier** [comment]
I tried, but it doesn't work :/

**Comment by alexfish** [comment]
Alright, will get this sorted as soon as I get some free time.

**Comment by jupier** [comment]
ok thank you

**Comment by alexfish** [comment]
@ridrum i've just imported the framework using CocoaPods into a test project and everything is working fine. I would make sure that you have the latest version (1.1.1) installed as i believe this issue may have been fixed in #17

**Comment by jupier** [comment]
Yeah I have the latest version. If I wish change the localizable strings, do I need to put another US2Localizable.strings in my project and change it ? The library will automatically use the new localizable file ?

**Comment by alexfish** [comment]
I would avoid trying to change the default strings in the file provided with the framework. You can just set the `localizedViolationString` property of the condition you want to update to whatever you want, can be loaded from your own localised string or just a hardcoded string, the world is your oyster!

**Comment by jupier** [comment]
Thanks alot for your answer. Have a nice day.

**Comment by alexfish** [comment]
no problem!
