### ISSUE TITLE
isKindOfClass / isMemberOfClass issue

### ISSUE THREAD

**Issue by ghost** [ustwo/US2FormValidator#26]
when i try to check if the US2ValidatorTextField isKindOfClass of UITextField - i got false. Not sure it's the way it should be

**Comment by alexfish** [comment]
You need to use `isSubclassOfClass`

https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/Reference/Reference.html#//apple_ref/occ/clm/NSObject/isSubclassOfClass:

**Comment by ghost** [comment]
Sorry - i mean US2ValidatorTextField object isKindOfClass of US2ValidatorTextField class

```
- (NSArray*)listOfValidatebleTextViews{
NSMutableArray* buffer = [NSMutableArray array];
for( UIView* view in self.view.subviews ){
    if ([view isKindOfClass:[US2ValidatorTextField class]]){
        [buffer addObject:view];
    }
}
return [NSArray arrayWithArray:buffer];
}
```

returns empty array, but i have some US2ValidatorTextField at view

**Comment by alexfish** [comment]
You are comparing `UIView` to `US2ValidatorTextField` they are not the same class so it is false. 

Can you post a question on stackoverflow? This isn't really related to the project, Thanks.
