### ISSUE TITLE
Multiple matches

### ISSUE THREAD

**Issue by alexfish** [ustwo/US2FormValidator#29]
It's not currently possible to allow for more than one match, for example:
must contain 2 numeric characters, the regex check currently checks for a single match. 

```
NSUInteger numberOfMatches = [regex numberOfMatchesInString:string options:0 range:NSMakeRange(0, string.length)];
success = numberOfMatches == 1;
```

We need a property on US2Condition that can set the number of matches required. It will need to support a specific number of matches as well as minimum and maximum.

**Comment by martinstolz** [comment]
@alexfish Version 1.1.2 should fix this issue for checking for two numeric characters. The regular expression check validates now only if the match range is the range of the whole string. Added a prior failing test case for US2ConditionNumeric.
