### ISSUE TITLE
File not Found on project

### ISSUE THREAD

**Issue by neetin** [ustwo/US2FormValidator#32]
I have just cloned this repo and tried to run sample app. Got this error

ld: library not found for -lUS2FormValidationFrameworkStaticLibrary

Also I did not find lUS2FormValidationFrameworkStaticLibrary.a anywhere in the project.

**Comment by alexfish** [comment]
Did you open the project using the workspace file? 

`US2FormValidationFrameworkSample.xcworkspace`
