### ISSUE TITLE
US2ConditonRange incorrect usage of NSRange

### ISSUE THREAD

**Issue by HeliumEnd** [ustwo/US2FormValidator#33]
`US2ConditionRange` is not using the `NSRange` correctly. It ignores the fact that `NSRange` location is the starting index where `NSRange` length counts from. 

For example, `(NSRange){0, 5}` would be a range between 0 and 5
`(NSRange){2,5}` would be a range between 2 and 7, not 2 and 5 as used in `US2ConditionRange`.

This how the range should be checked

```
string.length >= self.range.location && // start of the range is containted
string.length <= self.range.location + self.range.length; // end of the range is contained
```

**Comment by iceydee** [comment]
I agree. That is wrong. We should change the minor version number for this though as it may break some implementations that rely on this being wrong.

**Comment by martinstolz** [comment]
Thanks @NebulaFox, will have a look.

**Comment by martinstolz** [comment]
Okay, I think I will create a custom struct and keep our logic.

The string length has to be between X and Y.
Something like:
US2TextRange *textRange = [US2TextRange from:2 to:6];

"A" is invalid
"Ab" is valid
"Abcdef" is valid
"Abcdefg" is invalid

**Comment by martinstolz** [comment]
Started of a new branch where this is fixed: https://github.com/ustwo/US2FormValidator/tree/light-arc
