### ISSUE TITLE
URL validator

### ISSUE THREAD

**Issue by AlexDenisov** [ustwo/US2FormValidator#5]
URL validator says that this URL is correct

```
http://lol
```

I think you should use regular expression instead current solution.

**Comment by martinstolz** [comment]
Which URL validator are you using?
US2ValidatorURL or US2ValidatorShorthandURL?

The unit test for US2ConditionURL succeeds, but fails in your case for US2ConditionShorthandURL.
Anyway we'll take a look into it.

Thanks Alex.

**Comment by AlexDenisov** [comment]
I've use US2ConditionURL.
Thanks for response, I'll try US2ConditionShorthandURL.

**Comment by AlexDenisov** [comment]
US2ConditionShorthandURL works as needed, but in my case I need validation with protocol too (at least http/https).
Anyway thanks for your great library, I found it very usable within IBAForms.

**Comment by svoctor** [comment]
Cool, can we close this issue now then?

Thanks,

**Comment by AlexDenisov** [comment]
US2ValidatorURL still says that 

```
http://lol
```

is correct URL, so I don't know.

**Comment by martinstolz** [comment]
There is still one test failing on the URL validator.
So needs to be fixed. I am on it.

**Comment by martinstolz** [comment]
Fixed. Replaced iOS URL detector with regular expression. Added further tests to the project, all do succeed.

**Comment by AlexDenisov** [comment]
Great, thanks.

**Comment by rynaardb** [comment]
Awesome! Thanks for your effort!
