### ISSUE TITLE
US2Condition description incorrect

### ISSUE THREAD

**Issue by alexfish** [ustwo/US2FormValidator#8]
`US2Conditon` has an incorrect description when logged, this is due to an error in the ternary operator: 

```
[description appendString:[NSString stringWithFormat:@"\n <shouldAllowViolation: %@>", _shouldAllowViolation == 0 ? @"YES" : @"NO"]];
```

The error is at `US2Condition.m:74` YES & NO are the wrong way around.

**Comment by martinstolz** [comment]
Can you send a pull request with the fix, Alex?

**Comment by alexfish** [comment]
Fixed!
